spring.application.name=gestoralumnos

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:gestoralumnosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuraci\u00f3n de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Evita la cach\u00e9 de Thymeleaf durante el desarrollo
spring.thymeleaf.cache=false